package org.proteored.miapeapi.webservice.clients.miapeapi;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "MiapeDatabaseException", targetNamespace = "http://webservice.miapeapi.proteored.org/")
public class MiapeDatabaseException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private MiapeDatabaseException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public MiapeDatabaseException_Exception(String message, MiapeDatabaseException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public MiapeDatabaseException_Exception(String message, MiapeDatabaseException faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return
	 *         returns fault bean:
	 *         org.proteored.miapeapi.webservice.clients.miapeapi
	 *         .MiapeDatabaseException
	 */
	public MiapeDatabaseException getFaultInfo() {
		return faultInfo;
	}

}
