package org.proteored.miapeapi.webservice.clients.miapeapi;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "MiapeSecurityException", targetNamespace = "http://webservice.miapeapi.proteored.org/")
public class MiapeSecurityException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private MiapeSecurityException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public MiapeSecurityException_Exception(String message, MiapeSecurityException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public MiapeSecurityException_Exception(String message, MiapeSecurityException faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return
	 *         returns fault bean:
	 *         org.proteored.miapeapi.webservice.clients.miapeapi
	 *         .MiapeSecurityException
	 */
	public MiapeSecurityException getFaultInfo() {
		return faultInfo;
	}

}
