/*
 * InputTextDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package org.proteored.pacom.analysis.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * 
 * @author __USER__
 */
public class InputTextDialog extends javax.swing.JDialog {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8512374427052990524L;

	/** Creates new form InputTextDialog */
	public InputTextDialog(java.awt.Frame parent, String title, String explanation, Set<String> list) {
		super(parent, true);
		initComponents();
		this.jLabelExplanation.setText(explanation);
		this.setTitle(title);
		if (list != null && !list.isEmpty()) {
			StringBuilder sb = new StringBuilder();
			for (String line : list) {
				if (!"".equals(sb.toString()))
					sb.append("\n");
				sb.append(line);
			}
			this.jTextArea1.setText(sb.toString());
		}
		this.setVisible(true);
	}

	public List<String> getPastedInfo() {
		String pastedInfo = this.jTextArea1.getText();
		List<String> ret = new ArrayList<String>();
		if (!"".equals(pastedInfo)) {
			String[] splitted = pastedInfo.split("\n");
			for (String line : splitted) {
				String[] splitted2 = null;
				if (line.contains(";")) {
					splitted2 = line.split(";");
				} else if (line.contains(",")) {
					splitted2 = line.split(",");
				} else {
					splitted2 = new String[1];
					splitted2[0] = line;
				}
				for (String line2 : splitted2) {
					if (!"".equals(line2.trim()))
						ret.add(line2);
				}

			}
		}
		return ret;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jLabelExplanation = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jTextArea1.setColumns(20);
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1.setWrapStyleWord(true);
		jScrollPane1.setViewportView(jTextArea1);

		jScrollPane2.setViewportView(jScrollPane1);

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabelExplanation.setAutoscrolls(true);
		jLabelExplanation.setFocusTraversalPolicyProvider(true);
		jLabelExplanation.setFocusable(false);
		jLabelExplanation.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton1)
						.addComponent(jLabelExplanation, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jButton1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		setBounds((screenSize.width - 416) / 2, (screenSize.height - 338) / 2, 416, 338);
	}// </editor-fold>
		// GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				InputTextDialog dialog = new InputTextDialog(new javax.swing.JFrame(), "PRUEBA",
						"<html>Paste here a list of protein" + "<br/>" + " accessions (one for each line)</html>",
						null);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabelExplanation;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}