//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.06.22 at 09:36:55 PM PDT
//

package org.proteored.pacom.analysis.conf.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}CP_Node">
 *       &lt;sequence>
 *         &lt;element ref="{}CP_Replicate" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="curated" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "cpReplicate" })
@XmlRootElement(name = "CP_Experiment")
public class CPExperiment extends CPNode {

	@XmlElement(name = "CP_Replicate", required = true)
	protected List<CPReplicate> cpReplicate;
	@XmlAttribute(name = "curated", required = true)
	protected boolean curated;

	/**
	 * Gets the value of the cpReplicate property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cpReplicate property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCPReplicate().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CPReplicate }
	 * 
	 * 
	 */
	public List<CPReplicate> getCPReplicate() {
		if (cpReplicate == null) {
			cpReplicate = new ArrayList<CPReplicate>();
		}
		return cpReplicate;
	}

	/**
	 * Gets the value of the curated property.
	 * 
	 */
	public boolean isCurated() {
		return curated;
	}

	/**
	 * Sets the value of the curated property.
	 * 
	 */
	public void setCurated(boolean value) {
		curated = value;
	}

	@Override
	public String toString() {
		return getName();
	}
}
