//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.06.22 at 09:36:55 PM PDT
//

package org.proteored.pacom.analysis.conf.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}CP_Node">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="manually_created" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="local" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="local_project_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="miape_ms_id_ref" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CP_MSI")
public class CPMSI extends CPNode {

	@XmlAttribute(name = "id", required = true)
	protected int id;
	@XmlAttribute(name = "manually_created")
	protected Boolean manuallyCreated;
	@XmlAttribute(name = "local")
	protected Boolean local;
	@XmlAttribute(name = "local_project_name")
	protected String localProjectName;
	@XmlAttribute(name = "miape_ms_id_ref")
	protected Integer miapeMsIdRef;

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(int value) {
		id = value;
	}

	/**
	 * Gets the value of the manuallyCreated property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isManuallyCreated() {
		return manuallyCreated;
	}

	/**
	 * Sets the value of the manuallyCreated property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setManuallyCreated(Boolean value) {
		manuallyCreated = value;
	}

	/**
	 * Gets the value of the local property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isLocal() {
		return local;
	}

	/**
	 * Sets the value of the local property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setLocal(Boolean value) {
		local = value;
	}

	/**
	 * Gets the value of the localProjectName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocalProjectName() {
		return localProjectName;
	}

	/**
	 * Sets the value of the localProjectName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocalProjectName(String value) {
		localProjectName = value;
	}

	/**
	 * Gets the value of the miapeMsIdRef property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getMiapeMsIdRef() {
		return miapeMsIdRef;
	}

	/**
	 * Sets the value of the miapeMsIdRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMiapeMsIdRef(Integer value) {
		miapeMsIdRef = value;
	}

	@Override
	public String toString() {
		return getName();
	}
}
