//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.22 at 09:36:55 PM PDT 
//


package org.proteored.pacom.analysis.conf.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.proteored.miapeExtractor.analysis.conf.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.proteored.miapeExtractor.analysis.conf.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CPMSIList }
     * 
     */
    public CPMSIList createCPMSIList() {
        return new CPMSIList();
    }

    /**
     * Create an instance of {@link CPNode }
     * 
     */
    public CPNode createCPNode() {
        return new CPNode();
    }

    /**
     * Create an instance of {@link CPReplicate }
     * 
     */
    public CPReplicate createCPReplicate() {
        return new CPReplicate();
    }

    /**
     * Create an instance of {@link CPMSI }
     * 
     */
    public CPMSI createCPMSI() {
        return new CPMSI();
    }

    /**
     * Create an instance of {@link CPExperimentList }
     * 
     */
    public CPExperimentList createCPExperimentList() {
        return new CPExperimentList();
    }

    /**
     * Create an instance of {@link CPExperiment }
     * 
     */
    public CPExperiment createCPExperiment() {
        return new CPExperiment();
    }

    /**
     * Create an instance of {@link CPMSList }
     * 
     */
    public CPMSList createCPMSList() {
        return new CPMSList();
    }

    /**
     * Create an instance of {@link CPMS }
     * 
     */
    public CPMS createCPMS() {
        return new CPMS();
    }

}
