/*
 * TFrmInputTable.java Created on __DATE__, __TIME__
 */

package org.proteored.pacom.gui;

import java.awt.event.MouseEvent;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.AbstractTableModel;

import gnu.trove.map.hash.TIntObjectHashMap;

/**
 *
 * @author __USER__
 */
public class TFrmInputTable extends javax.swing.JDialog {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3170154557975726634L;
	// variables.....
	public static final String[] instrument_head = new String[] { "Name", "Manufacturer", "IonSource(s)", "Analyzer(s)",
			"Activation" };
	private String[] project_head;
	// public static final int INTRUMENT_MODE = 1;
	public static final int PROJECT_MODE = 0;
	// Para las proporciones
	private int[] project_propor = {};
	// En principio el modelo va a ser abstracto.
	private AbstractTableModel TableModel;
	// la Seleccion
	private String userSelection;
	// ParentForm
	private final MiapeExtractionFrame parentForm;

	private boolean firstClick = false;
	private long firstClickTime;
	private String previousUserSelection;

	public TFrmInputTable(MiapeExtractionFrame parentForm, boolean modal, TIntObjectHashMap<String> miapeProjects) {
		super(parentForm, modal);
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
		initComponents();
		this.parentForm = parentForm;
		project_head = new String[] { "ID", "Name", "Date" };
		project_propor = new int[] { 5, 35, 10 };
		userSelection = "NO SELECTION";
		myInit(miapeProjects);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel_head = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable_contents = new javax.swing.JTable();
		jButtonOK = new javax.swing.JButton();
		jButtonCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("");

		jTable_contents
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jTable_contents.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click_or_double_click(evt);
			}
		});
		jScrollPane1.setViewportView(jTable_contents);

		jButtonOK.setText("OK");
		jButtonOK.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOKActionPerformed(evt);
			}
		});

		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel_head)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jButtonOK)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButtonCancel)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel_head)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonCancel).addComponent(jButtonOK))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width - dialogSize.width) / 2, (screenSize.height - dialogSize.height) / 2);
	}// </editor-fold>
		// GEN-END:initComponents

	private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {
		// Se chequea la opcion y crea un objecto para enviar....
		// Ahora mismo un String....
		if (jTable_contents.getSelectedRow() >= 0) {

			// if (FormMode == INTRUMENT_MODE) {
			// userSelection = (String) jTable_contents.getValueAt(
			// jTable_contents.getSelectedRow(), 0);
			// parentForm.fillInstrumentUserSelection(userSelection,
			// jTable_contents.getSelectedRow());
			// } else {
			userSelection = (String) jTable_contents.getValueAt(jTable_contents.getSelectedRow(), 1);
			parentForm.fillProjectUserSelection(userSelection);
			// }
		}
		setVisible(false);
	}

	private void click_or_double_click(MouseEvent evt) {
		final long currentTimeMillis = System.currentTimeMillis();
		if (firstClick) {
			// this is the second click
			if (currentTimeMillis - firstClickTime < 300) {
				if (jTable_contents.getSelectedRow() >= 0) {
					String currentUserSelection = jTable_contents.getValueAt(jTable_contents.getSelectedRow(), 0)
							.toString();
					if (currentUserSelection.equals(previousUserSelection)) {
						jButtonOKActionPerformed(null);
						return;
					}
				}
			}
		}
		firstClick = true;
		firstClickTime = currentTimeMillis;
		if (jTable_contents.getSelectedRow() >= 0) {
			previousUserSelection = jTable_contents.getValueAt(jTable_contents.getSelectedRow(), 0).toString();
		}

	}

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {

		// if (FormMode == INTRUMENT_MODE) {
		// userSelection = "Not entered";
		// parentForm.fillInstrumentUserSelection(userSelection, -1);
		// } else {
		if (userSelection != null && !"".equals(userSelection) && !"NO SELECTION".equals(userSelection))
			parentForm.fillProjectUserSelection(userSelection);
		// }
		setVisible(false);
	}

	public MiapeExtractionFrame getParentForm() {
		return parentForm;
	}

	private void myInit(TIntObjectHashMap<String> Data) {

		// Este metodo cambia el label de la cabecera y los contenidos de la
		// tabla.

		// if (FormMode == INTRUMENT_MODE) {
		// jLabel_head.setText("Select an instrument");
		// this.setTitle("Instruments");
		// TableModel = new TInstrumentModelTable(instrument_head, Data);
		// jTable_contents.setModel(TableModel);
		// initTableWidth(jTable_contents, instrument_propor);
		// } else {
		jLabel_head.setText("Select a project from the list");
		setTitle("Projects");
		TableModel = new TMIAPEProjectModelTable(project_head, Data);
		jTable_contents.setModel(TableModel);
		initTableWidth(jTable_contents, project_propor);
		// }
		jTable_contents.setVisible(true);
	}

	private void initTableWidth(javax.swing.JTable _table, int[] propor) {
		int table_width = _table.getWidth();
		for (int i = 0; i < propor.length; i++) {
			int _aux = ((table_width * propor[i]) / 100);
			_table.getColumnModel().getColumn(i).setWidth(_aux);
			_table.getColumnModel().getColumn(i).setPreferredWidth(_aux);
		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonCancel;
	private javax.swing.JButton jButtonOK;
	public javax.swing.JLabel jLabel_head;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable_contents;
	// End of variables declaration//GEN-END:variables

}