package org.proteored.miapeapi.webservice.clients.miapeextractor;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MiapeExtractorService service = new MiapeExtractorService();
 * MiapeExtractorDelegate portType = service.getMiapeExtractorPort();
 * portType.main(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MiapeExtractorService", targetNamespace = "http://webservice.miapeconverter.miapeapi.proteored.org/", wsdlLocation = "file:/C:/Users/Salva/workspace/miape-extractor-webservice/WebRoot/WEB-INF/wsdl/MiapeExtractorService.wsdl")
public class MiapeExtractorService extends Service {

	private final static URL MIAPEEXTRACTORSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.proteored.miapeapi.webservice.clients.miapeextractor.MiapeExtractorService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.proteored.miapeapi.webservice.clients.miapeextractor.MiapeExtractorService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/C:/Users/Salva/workspace/miape-extractor-webservice/WebRoot/WEB-INF/wsdl/MiapeExtractorService.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Salva/workspace/miape-extractor-webservice/WebRoot/WEB-INF/wsdl/MiapeExtractorService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MIAPEEXTRACTORSERVICE_WSDL_LOCATION = url;
	}

	public MiapeExtractorService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MiapeExtractorService() {
		super(MIAPEEXTRACTORSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.miapeconverter.miapeapi.proteored.org/",
				"MiapeExtractorService"));
	}

	/**
	 * 
	 * @return returns MiapeExtractorDelegate
	 */
	@WebEndpoint(name = "MiapeExtractorPort")
	public MiapeExtractorDelegate getMiapeExtractorPort() {
		return super.getPort(new QName(
				"http://webservice.miapeconverter.miapeapi.proteored.org/",
				"MiapeExtractorPort"), MiapeExtractorDelegate.class);
	}

}
