/*
 * CurateExperimentNameCreatorDialog.java
 * Created on __DATE__, __TIME__
 */

package org.proteored.miapeExtractor.analysis.gui;

import org.proteored.miapeapi.experiment.model.Experiment;
import org.proteored.miapeapi.experiment.model.ExperimentList;

/**
 * 
 * @author __USER__
 */
public class CuratedExperimentNameCreatorDialog extends javax.swing.JDialog {
	private final ExperimentList experimentList;

	/** Creates new form CurateExperimentNameCreatorDialog */
	CuratedExperimentNameCreatorDialog(java.awt.Frame parent,
			ExperimentList experimentList) {
		super(parent, true);
		initComponents();
		this.experimentList = experimentList;
		updateExperimentLabel();
		this.pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jRadioButtonPrefix = new javax.swing.JRadioButton();
		jRadioButtonSufix = new javax.swing.JRadioButton();
		jRadioButtonNoModify = new javax.swing.JRadioButton();
		jPanel2 = new javax.swing.JPanel();
		jLabelExperimentNames = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jTextField = new javax.swing.JTextField();
		jButtonOK = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		buttonGroup1.add(jRadioButtonPrefix);
		jRadioButtonPrefix.setText("add a prefix");
		jRadioButtonPrefix
				.addActionListener(new java.awt.event.ActionListener() {
					@Override
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonPrefixActionPerformed(evt);
					}
				});

		buttonGroup1.add(jRadioButtonSufix);
		jRadioButtonSufix.setText("add a sufix");
		jRadioButtonSufix
				.addActionListener(new java.awt.event.ActionListener() {
					@Override
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonSufixActionPerformed(evt);
					}
				});

		buttonGroup1.add(jRadioButtonNoModify);
		jRadioButtonNoModify.setSelected(true);
		jRadioButtonNoModify
				.setText("don't modifiy the original experiment names");
		jRadioButtonNoModify
				.addActionListener(new java.awt.event.ActionListener() {
					@Override
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonNoModifyActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jRadioButtonPrefix)
														.addComponent(
																jRadioButtonSufix)
														.addComponent(
																jRadioButtonNoModify))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jRadioButtonPrefix)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jRadioButtonSufix)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jRadioButtonNoModify)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(),
				"Experiment names"));

		jLabelExperimentNames
				.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabelExperimentNames,
								javax.swing.GroupLayout.DEFAULT_SIZE, 466,
								Short.MAX_VALUE).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addComponent(jLabelExperimentNames,
								javax.swing.GroupLayout.DEFAULT_SIZE, 101,
								Short.MAX_VALUE).addContainerGap()));

		jTextField.setText("curated");
		jTextField.setEnabled(false);
		jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyReleased(java.awt.event.KeyEvent evt) {
				jTextFieldKeyReleased(evt);
			}
		});

		jButtonOK.setText("OK");
		jButtonOK.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOKActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																190,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButtonOK))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												27, Short.MAX_VALUE)
										.addComponent(jButtonOK)
										.addContainerGap()));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12));
		jLabel2.setText("Here you can modify the final name of the curated experiments. Press OK when you finish.");
		jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addComponent(
																		jPanel2,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jPanel3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										46,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jPanel3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 543) / 2, (screenSize.height - 366) / 2,
				543, 366);
	}// </editor-fold>
		// GEN-END:initComponents

	private void jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {
		updateExperimentLabel();
	}

	private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void jRadioButtonNoModifyActionPerformed(
			java.awt.event.ActionEvent evt) {
		if (this.jRadioButtonNoModify.isSelected())
			this.jTextField.setEnabled(false);
		updateExperimentLabel();

	}

	private void jRadioButtonPrefixActionPerformed(
			java.awt.event.ActionEvent evt) {
		if (this.jRadioButtonPrefix.isSelected())
			this.jTextField.setEnabled(true);
		updateExperimentLabel();

	}

	private void jRadioButtonSufixActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.jRadioButtonSufix.isSelected())
			this.jTextField.setEnabled(true);
		updateExperimentLabel();
	}

	public String getExperimentName(String experimentName) {
		String ret = experimentName;
		if (this.jRadioButtonPrefix.isSelected())
			ret = this.jTextField.getText() + ret;
		else if (this.jRadioButtonSufix.isSelected())
			ret = ret + this.jTextField.getText();
		return ret;
	}

	private void updateExperimentLabel() {
		if (this.experimentList != null) {
			StringBuilder sb = new StringBuilder();
			sb.append("<html><ul>");
			for (Experiment experiment : this.experimentList.getExperiments()) {
				String name = experiment.getName();
				if (this.jRadioButtonPrefix.isSelected())
					name = this.jTextField.getText() + name;
				else if (this.jRadioButtonSufix.isSelected())
					name = name + this.jTextField.getText();

				sb.append("<li>" + name + "</li>");
			}
			sb.append("</ul></html>");
			this.jLabelExperimentNames.setText(sb.toString());
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				CuratedExperimentNameCreatorDialog dialog = new CuratedExperimentNameCreatorDialog(
						new javax.swing.JFrame(), null);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButtonOK;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabelExperimentNames;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JRadioButton jRadioButtonNoModify;
	private javax.swing.JRadioButton jRadioButtonPrefix;
	private javax.swing.JRadioButton jRadioButtonSufix;
	private javax.swing.JTextField jTextField;
	// End of variables declaration//GEN-END:variables

}