/*
 * MainQueries.java
 * Created on __DATE__, __TIME__
 */

package org.proteored.miapeExtractor.gui.queries.gui;

/**
 * 
 * @author __USER__
 */
public class MainQueries extends javax.swing.JFrame {

	/** Creates new form MainQueries */
	public MainQueries() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextFieldProteinACC = new javax.swing.JTextField();
		jTextFieldPeptideSequence = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jButtonSearchProteinACC = new javax.swing.JButton();
		jButtonSearchPeptideSequence = new javax.swing.JButton();
		jPanelResults = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Protein accession");

		jLabel2.setText("Peptide sequence");

		jButtonSearchProteinACC.setText("search");
		jButtonSearchProteinACC.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSearchProteinACCActionPerformed(evt);
			}
		});

		jButtonSearchPeptideSequence.setText("search");
		jButtonSearchPeptideSequence.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSearchPeptideSequenceActionPerformed(evt);
			}
		});

		jPanelResults.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
		jPanelResults.setLayout(jPanelResultsLayout);
		jPanelResultsLayout.setHorizontalGroup(jPanelResultsLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 673, Short.MAX_VALUE));
		jPanelResultsLayout.setVerticalGroup(jPanelResultsLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 325, Short.MAX_VALUE));

		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12));
		jLabel3.setText("THIS IS JUST A BETA VERSION");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(75, 75, 75)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jTextFieldPeptideSequence,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										215,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jTextFieldProteinACC,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										215,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButtonSearchProteinACC)
																				.addComponent(
																						jButtonSearchPeptideSequence)))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jPanelResults,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(258, 258, 258)
																.addComponent(jLabel3)))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel3)
						.addGap(41, 41, 41)
						.addGroup(
								layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jTextFieldProteinACC,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonSearchProteinACC))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(jTextFieldPeptideSequence,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonSearchPeptideSequence))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void jButtonSearchPeptideSequenceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonSearchProteinACCActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MainQueries().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonSearchPeptideSequence;
	private javax.swing.JButton jButtonSearchProteinACC;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanelResults;
	private javax.swing.JTextField jTextFieldPeptideSequence;
	private javax.swing.JTextField jTextFieldProteinACC;
	// End of variables declaration//GEN-END:variables

}