
package org.proteored.miapeExtractor.utils.picr;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* AccessionMapperService service = new AccessionMapperService();
* AccessionMapperInterface portType = service.getAccessionMapperPort();
* portType.getUPIForSequence(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "AccessionMapperService", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", wsdlLocation = "http://www.ebi.ac.uk/Tools/picr/service?wsdl")
public class AccessionMapperService
    extends Service
{

    private final static URL ACCESSIONMAPPERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.proteored.miapeExtractor.utils.picr.AccessionMapperService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.proteored.miapeExtractor.utils.picr.AccessionMapperService.class.getResource(".");
            url = new URL(baseUrl, "http://www.ebi.ac.uk/Tools/picr/service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.ebi.ac.uk/Tools/picr/service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCESSIONMAPPERSERVICE_WSDL_LOCATION = url;
    }

    public AccessionMapperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccessionMapperService() {
        super(ACCESSIONMAPPERSERVICE_WSDL_LOCATION, new QName("http://www.ebi.ac.uk/picr/AccessionMappingService", "AccessionMapperService"));
    }

    /**
     * 
     * @return
     *     returns AccessionMapperInterface
     */
    @WebEndpoint(name = "AccessionMapperPort")
    public AccessionMapperInterface getAccessionMapperPort() {
        return super.getPort(new QName("http://www.ebi.ac.uk/picr/AccessionMappingService", "AccessionMapperPort"), AccessionMapperInterface.class);
    }

}
